const Events = {
  ERROR: 'ERROR',
  SKIP: 'SKIP',
  COMPLETION: 'COMPLETION',
  BOARDUPDATE: 'BOARDUPDATE',
  NEXTTURN: 'NEXTTURN',
  REVEAL: 'REVEAL',
  STATECHANGE: 'STATECHANGE',
  END: 'END',
};

export default Events;
